spring:
  application:
    name: OrderingService
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8080/realms/myrealm #Auth server
server:
  port: 8081


